spring.application.name=gestor-tareas
spring.datasource.url=jdbc:h2:mem:gestordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:gestor_de_tareas.sql
spring.jpa.hibernate.ddl-auto=none