
DROP TABLE IF EXISTS tareas;
DROP TABLE IF EXISTS proyectos;

CREATE TABLE proyectos (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR(120) NOT NULL,
  descripcion  TEXT,
  estado       VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_fin    DATE,
  creado_en    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uk_proyectos_nombre UNIQUE (nombre),
  CONSTRAINT chk_proyectos_estado
    CHECK (estado IN ('ACTIVO', 'PAUSADO', 'FINALIZADO', 'CANCELADO')),
  CONSTRAINT chk_proyectos_fechas
    CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE tareas (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo        VARCHAR(150) NOT NULL,
  descripcion   TEXT,
  estado        VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  prioridad     VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
  fecha_limite  DATE,
  completada_en TIMESTAMP,
  proyecto_id   BIGINT NOT NULL,
  creado_en     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_tareas_proyecto
    FOREIGN KEY (proyecto_id)
    REFERENCES proyectos(id)
    ON DELETE CASCADE,

  CONSTRAINT chk_tareas_estado
    CHECK (estado IN ('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA')),
  CONSTRAINT chk_tareas_prioridad
    CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
  CONSTRAINT chk_tareas_completada
    CHECK (
      (estado = 'COMPLETADA' AND completada_en IS NOT NULL)
      OR
      (estado <> 'COMPLETADA')
    )
);


CREATE INDEX idx_tareas_proyecto_id ON tareas(proyecto_id);
CREATE INDEX idx_tareas_estado ON tareas(estado);
CREATE INDEX idx_tareas_prioridad ON tareas(prioridad);
CREATE INDEX idx_tareas_fecha_limite ON tareas(fecha_limite);


INSERT INTO proyectos (nombre, descripcion, estado, fecha_inicio, fecha_fin) VALUES
  ('Desarrollo Web Fullstack', 'Proyecto académico con backend Spring Boot y frontend Angular.', 'ACTIVO', '2026-05-20', NULL),
  ('Organización Personal', 'Gestión de tareas personales y recordatorios importantes.', 'ACTIVO', '2026-05-21', NULL),
  ('Campaña de Marketing', 'Planificación de entregables, revisiones y fechas límite.', 'PAUSADO', '2026-05-10', '2026-06-30');

INSERT INTO tareas (titulo, descripcion, estado, prioridad, fecha_limite, completada_en, proyecto_id) VALUES
  ('Crear entidades JPA', 'Crear Proyecto y Tarea con relación 1:N.', 'COMPLETADA', 'ALTA', '2026-05-22', CURRENT_TIMESTAMP, 1),
  ('Configurar H2 modo PostgreSQL', 'Añadir configuración de conexión en application.properties.', 'EN_PROGRESO', 'ALTA', '2026-05-24', NULL, 1),
  ('Crear ProyectoController', 'Exponer endpoints GET y POST para proyectos.', 'PENDIENTE', 'MEDIA', '2026-05-27', NULL, 1),
  ('Crear TareaController', 'Exponer endpoints GET y POST para tareas.', 'PENDIENTE', 'MEDIA', '2026-05-28', NULL, 1),
  ('Preparar README', 'Documentar cómo levantar backend y frontend.', 'PENDIENTE', 'BAJA', '2026-06-01', NULL, 1),

  ('Comprar material de estudio', 'Preparar recursos necesarios para avanzar el proyecto.', 'PENDIENTE', 'MEDIA', '2026-05-25', NULL, 2),
  ('Revisar agenda semanal', 'Ordenar tareas por prioridad y fecha límite.', 'EN_PROGRESO', 'MEDIA', '2026-05-26', NULL, 2),

  ('Diseñar calendario de publicaciones', 'Crear planificación inicial de publicaciones.', 'COMPLETADA', 'MEDIA', '2026-05-18', CURRENT_TIMESTAMP, 3),
  ('Revisar piezas gráficas', 'Validar materiales antes de publicar.', 'PENDIENTE', 'ALTA', '2026-06-05', NULL, 3);

