-- =========================================================
-- Base de datos: Gestor de Proyectos y Tareas
-- Backend: Java + Spring Boot + Spring Data JPA
-- BBDD: H2 en memoria con compatibilidad PostgreSQL
-- =========================================================
--
-- application.properties recomendado:
-- spring.datasource.url=jdbc:h2:mem:gestor_tareas;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
-- spring.datasource.driverClassName=org.h2.Driver
-- spring.datasource.username=sa
-- spring.datasource.password=
-- spring.h2.console.enabled=true
-- spring.jpa.hibernate.ddl-auto=none
-- spring.jpa.defer-datasource-initialization=true
-- spring.sql.init.mode=always
--
-- Este script cumple:
-- 1) Persistencia en base de datos relacional.
-- 2) Operaciones básicas CRUD desde API REST.
-- 3) Relación 1:N entre proyectos y tareas.
-- 4) Datos iniciales para probar GET /api/proyectos y GET /api/proyectos/{id}.

DROP TABLE IF EXISTS tareas;
DROP TABLE IF EXISTS proyectos;

-- =========================
-- TABLA PRINCIPAL: PROYECTOS
-- Relación 1:N -> un proyecto tiene muchas tareas.
-- En Java:
--   Proyecto -> @OneToMany(mappedBy = "proyecto")
--   Tarea    -> @ManyToOne @JoinColumn(name = "proyecto_id")
-- =========================
CREATE TABLE proyectos (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR(120) NOT NULL,
  descripcion  TEXT,
  estado       VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_fin    DATE,
  creado_en    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT uk_proyectos_nombre UNIQUE (nombre),
  CONSTRAINT chk_proyectos_estado
    CHECK (estado IN ('ACTIVO', 'PAUSADO', 'FINALIZADO', 'CANCELADO')),
  CONSTRAINT chk_proyectos_fechas
    CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

-- =========================
-- TABLA HIJA: TAREAS
-- Muchas tareas pertenecen a un único proyecto.
-- =========================
CREATE TABLE tareas (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo        VARCHAR(150) NOT NULL,
  descripcion   TEXT,
  estado        VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  prioridad     VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
  fecha_limite  DATE,
  completada_en TIMESTAMP,
  proyecto_id   BIGINT NOT NULL,
  creado_en     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_tareas_proyecto
    FOREIGN KEY (proyecto_id)
    REFERENCES proyectos(id)
    ON DELETE CASCADE,

  CONSTRAINT chk_tareas_estado
    CHECK (estado IN ('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA')),
  CONSTRAINT chk_tareas_prioridad
    CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
  CONSTRAINT chk_tareas_completada
    CHECK (
      (estado = 'COMPLETADA' AND completada_en IS NOT NULL)
      OR
      (estado <> 'COMPLETADA')
    )
);

-- Índices útiles para consultas REST.
CREATE INDEX idx_tareas_proyecto_id ON tareas(proyecto_id);
CREATE INDEX idx_tareas_estado ON tareas(estado);
CREATE INDEX idx_tareas_prioridad ON tareas(prioridad);
CREATE INDEX idx_tareas_fecha_limite ON tareas(fecha_limite);

-- =========================
-- DATOS DE PRUEBA
-- Sirven para que la aplicación arranque con contenido visible.
-- =========================

INSERT INTO proyectos (nombre, descripcion, estado, fecha_inicio, fecha_fin) VALUES
  ('Desarrollo Web Fullstack', 'Proyecto académico con backend Spring Boot y frontend Angular.', 'ACTIVO', '2026-05-20', NULL),
  ('Organización Personal', 'Gestión de tareas personales y recordatorios importantes.', 'ACTIVO', '2026-05-21', NULL),
  ('Campaña de Marketing', 'Planificación de entregables, revisiones y fechas límite.', 'PAUSADO', '2026-05-10', '2026-06-30');

INSERT INTO tareas (titulo, descripcion, estado, prioridad, fecha_limite, completada_en, proyecto_id) VALUES
  ('Crear entidades JPA', 'Crear Proyecto y Tarea con relación 1:N.', 'COMPLETADA', 'ALTA', '2026-05-22', CURRENT_TIMESTAMP, 1),
  ('Configurar H2 modo PostgreSQL', 'Añadir configuración de conexión en application.properties.', 'EN_PROGRESO', 'ALTA', '2026-05-24', NULL, 1),
  ('Crear ProyectoController', 'Exponer endpoints GET y POST para proyectos.', 'PENDIENTE', 'MEDIA', '2026-05-27', NULL, 1),
  ('Crear TareaController', 'Exponer endpoints GET y POST para tareas.', 'PENDIENTE', 'MEDIA', '2026-05-28', NULL, 1),
  ('Preparar README', 'Documentar cómo levantar backend y frontend.', 'PENDIENTE', 'BAJA', '2026-06-01', NULL, 1),

  ('Comprar material de estudio', 'Preparar recursos necesarios para avanzar el proyecto.', 'PENDIENTE', 'MEDIA', '2026-05-25', NULL, 2),
  ('Revisar agenda semanal', 'Ordenar tareas por prioridad y fecha límite.', 'EN_PROGRESO', 'MEDIA', '2026-05-26', NULL, 2),

  ('Diseñar calendario de publicaciones', 'Crear planificación inicial de publicaciones.', 'COMPLETADA', 'MEDIA', '2026-05-18', CURRENT_TIMESTAMP, 3),
  ('Revisar piezas gráficas', 'Validar materiales antes de publicar.', 'PENDIENTE', 'ALTA', '2026-06-05', NULL, 3);

-- =========================
-- CONSULTAS DE COMPROBACIÓN
-- =========================
-- Listar proyectos:
-- SELECT * FROM proyectos;
--
-- Ver tareas de un proyecto:
-- SELECT * FROM tareas WHERE proyecto_id = 1;
--
-- Ver detalle combinado:
-- SELECT
--   p.id AS proyecto_id,
--   p.nombre AS proyecto,
--   t.id AS tarea_id,
--   t.titulo AS tarea,
--   t.estado,
--   t.prioridad
-- FROM proyectos p
-- LEFT JOIN tareas t ON t.proyecto_id = p.id
-- ORDER BY p.id, t.id;
